version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper

  auth-service:
    build: ./auth-service
    depends_on:
      - kafka
      - zookeeper

  playlist-service:
    build: ./playlist-service
    depends_on:
      - kafka
      - zookeeper

  search-service:
    build: ./search-service
    depends_on:
      - kafka
      - zookeeper

  player-service:
    build: ./player-service
    depends_on:
      - kafka
      - zookeeper

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
